#!/usr/bin/python

import sys
import os
import argparse
from lxml import etree as ET

XMLNS = '{http://www.w3.org/XML/1998/namespace}'
TEINS = '{http://www.tei-c.org/ns/1.0}'


def ns(s):
    return s.format(xml=XMLNS, tei=TEINS)


def clean_tree(tree):
    """Remove things that don't make good text"""
    for tag in ('table', 'note', 'figure', 'pb'):
        for el in tree.findall(ns('.//{tei}p//{tei}%s' % tag)):
            del el[:]

    find_choice = ET.ETXPath(ns("//{tei}choice"))
    for c in find_choice(tree):
        # pick one choice. the last (second) one is usually the
        # <reg> one with hyphens removed.
        del c[:-1]


def extract_body_parts(bodyxml):
    """Get the cleaned up text from an xml element"""
    doc = []
    find_text = ET.ETXPath(ns(".//{tei}p"
                              "|.//{tei}head[@rend='run-in']"
                              ))
    prefix = ''
    for p in find_text(bodyxml):
        para = ET.tostring(p, method='text', encoding='utf8').strip()
        if p.get('rend') == 'run-in':
            prefix += para.strip() + ' '
        else:
            doc.append(prefix + para)
            prefix = ''

    return '\n\n'.join(doc)


def extract_body(fn):
    tree = ET.parse(fn)
    clean_tree(tree)
    body_xml = tree.find(ns('//{tei}text'))
    body = extract_body_parts(body_xml)
    return body


def main():
    global DEST_DIR
    parser = argparse.ArgumentParser()
    parser.add_argument('books', nargs='+',
                        help="convert these xml files")
    args = parser.parse_args()

    for book in args.books:
        print extract_body(book)

main()
